# -*- coding: utf-8 -*-
"""W4_Mahir.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1725dKI8RmkgyXIzBExyK97N6RhnwmrLp
"""

#1
class Book:
    def __init__(self, title, author, price):
        self.title = title
        self.author = author
        self.price = price
    def view(self):
        return f"{self.title} by {self.author}, price ${self.price}"

Mybook = Book('Python Course', 'Eric Matthes', 23)
print(Mybook.view())

#2
import math

class Circle:
  def __init__(self, a, b, r):
    self.a = a
    self.b = b
    self.r = r

  def area(self):
    return math.pi * (self.r ** 2)

  def perimeter(self):
    return 2 * math.pi * self.r

  def testBelongs(self, x, y):
    return (x-self.a)**2 + (y-self.b)**2 - self.r**2 == 0

class Cylinder(Circle):
  def __init__(self, a, b, r, height):
    super().__init__(a, b, r)
    self.height = height

  def volume(self):
    return self.area() * self.height

#3
class BankAccount:
  def __init__(self, accountNumber, name, balance):
    self.accountNumber = accountNumber
    self.name = name
    self.balance = balance

  def Deposite(self, deposite):
    self.balance += deposite

  def Withdrawal(self, withdraw):
    self.balance -= withdraw

  def bankFees(self):
    self.fee = self.balance * 5 / 100

  def display(self):
    print(f"Account Holder: {self.name}")
    print(f"Account Balance: {self.balance}")
    print(f"Bank fees: {self.fee}")
    print(f"Adjusted Balance: {self.balance - self.fee}")